### ISSUE TITLE
missing `typing_extensions` dependency

### ISSUE THREAD

**Issue by petergaultney** [xoeye/typecats#9]
I think this (in the setup.py) would fix it:

```
        "typing_extensions >= 3.7;python_version<'3.8'",
```

this is coming in version 1.8 I believe, but in the meantime it would be nice to fix this for 1.7.x

**Comment by jwsloan** [comment]
I'll check that out tomorrow. Thanks for point it out!

**Comment by petergaultney** [comment]
I _think_ you might need to bump the version manually (and the changelog), and then turn the existing release draft into an actual published draft.  1.7.1, I think.

I can't see any of this - all I can see for sure is that PyPi doesn't have a release yet.

**Comment by jwsloan** [comment]
The same thought occurred to me as soon as this merged. Then I forgot to actually do it. I'll get to that today.
